#!/usr/bin/env bash
# install nginx and change the default web page to Hello World!

sudo apt-get -y update 
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
sudo ufw enable
sudo service nginx start
sudo mkdir /myroot
touch /myroot/index.html
sudo echo 'Hello World!' > /myroot/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /myroot;
     index       index.html;
}
" > /etc/nginx/sites-available/default
sudo service nginx restart
