#!/usr/bin/env bash
# install nginx and change the default web page to Hello World!

apt-get -y update 
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
ufw --force enable
service nginx start
mkdir /myroot
touch /myroot/index.html
echo 'Hello World!' > /myroot/index.html
sed -i 's+root /var/www/html+root /myroot+' /etc/nginx/sites-available/default
service nginx restart
