#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

apt-get -y update 
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
ufw enable
service nginx start
mkdir /myroot
touch /myroot/index.html /myroot/custom_404.html
echo 'Hello World!' > /myroot/index.html
echo "Ceci n'est pas une page" > /myroot/index.html
sed -i 's+location+error_page 404 /custom_404.html\nlocation = /custom_404.html {root /myroot;\ninternal;' /etc/nginx/sites-available/default
service nginx restart
