#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

apt-get -y update 
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
ufw --force enable
mkdir -p myroot
touch myroot/index.html myroot/custom_404.html
echo 'Hello World!' > myroot/index.html
echo "Ceci n'est pas une page" > myroot/custom_404.html
service nginx start
sed -i  's+root /var/www/html+root /myroot+1' /etc/nginx/sites-available/default
sed -i 's/server_name _/server_name .joseun.tech/' /etc/nginx/sites-available/default
sed -i '/server_name .joseun.tech;/a\\n\t  error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\troot /myroot;>
sed -i '/server_name .joseun.tech;/a\\n\t rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/>
service nginx restart