#!/usr/bin/env bash
# Configures an Nginx server to add a custom Nginx response header.
apt-get -y update 
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
service nginx start
mkdir myroot
touch myroot/index.html myroot/custom_404.html
echo 'Hello World!' > myroot/index.html
echo "Ceci n'est pas une page" > myroot/custom_404.html
sed -i 's+root /var/www/html+root /myroot+' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i 's/server_name _;/server_name .joseun.tech;/' /etc/nginx/sites-available/default
sed -i 's+location / {+error_page 404 /custom_404.html\n\tlocation = /custom_404.html {\n\troot /myroot;\n\tinternal;\n+' /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/s/$/\n\taddheader X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
