#!/usr/bin/env bash
# "bad luck from China" 4th iteration
# "bad luck from Japan" 9th iteration
# "bad luck from Italy" 17th iteration

COUNTER=1
while [ "$COUNTER" -le 20 ];
do
    echo "$COUNTER"
    case "$COUNTER" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let COUNTER=COUNTER+1
done
