#!/usr/bin/env bash
#  Script bash that displays the time for 12 hours and 59 minutes

HOUR=0
while [ $HOUR -le 12 ];
do
    echo "Hour: $HOUR"
    MINUTE=1
    while [ $MINUTE -le 59 ];
    do
	echo  $MINUTE
	let MINUTE=MINUTE+1
    done
    let HOUR=HOUR+1
done
